#!/usr/bin/env bash
# Release helper for NativeBeam.
#
# Enforces the trunk-based + release-branch workflow documented in
# docs/BRANCHING.md:
#
#   - Stable versions (e.g. 0.2.0) MUST be cut from a `release/v*` branch.
#   - Prereleases (e.g. 0.2.0-rc.1, 0.3.0-alpha.4) may be cut from `master`,
#     a `release/v*`, or any `feature/*` branch.
#
# Steps: branch check -> clean tree -> tag-doesn't-exist -> dotnet test ->
# rewrite <Version> in Directory.Build.props -> commit -> annotated tag ->
# push current branch + tag -> open backmerge PR via `gh` (best effort).
#
# Usage:
#   scripts/release.sh <version> [--remote <name>] [--skip-tests] [--no-pr]
#
# Examples:
#   scripts/release.sh 0.3.0-alpha.1                # from master
#   scripts/release.sh 0.2.0                        # from release/v0.2
#   scripts/release.sh 0.2.0 --remote upstream

set -Eeuo pipefail

VERSION=""
REMOTE="origin"
SKIP_TESTS=0
OPEN_PR=1

usage() {
    sed -n '2,22p' "$0" | sed 's/^# \{0,1\}//'
    exit "${1:-1}"
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        -h|--help)            usage 0 ;;
        --remote)
            [[ $# -ge 2 ]] || { echo "--remote requires an argument" >&2; exit 1; }
            REMOTE="$2"; shift 2 ;;
        --skip-tests)         SKIP_TESTS=1; shift ;;
        --no-pr)              OPEN_PR=0; shift ;;
        -*)                   echo "Unknown option: $1" >&2; usage 1 ;;
        *)
            if [[ -n "$VERSION" ]]; then
                echo "Unexpected positional argument: $1" >&2
                usage 1
            fi
            VERSION="$1"; shift ;;
    esac
done

[[ -n "$VERSION" ]] || { echo "error: <version> is required" >&2; usage 1; }

if [[ ! "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z.-]+)?$ ]]; then
    echo "error: '$VERSION' is not a valid semantic version (e.g. 0.2.0 or 0.3.0-rc.1)" >&2
    exit 1
fi

# True when version has a `-prerelease` suffix.
IS_PRERELEASE=0
[[ "$VERSION" == *-* ]] && IS_PRERELEASE=1

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "$SCRIPT_DIR/.." && pwd)"
PROPS_PATH="$REPO_ROOT/Directory.Build.props"
TAG="v$VERSION"

step() { printf '\033[36m==> %s\033[0m\n' "$*"; }

cd "$REPO_ROOT"

step "Verifying current branch matches version policy"
BRANCH="$(git rev-parse --abbrev-ref HEAD)"
if [[ "$IS_PRERELEASE" -eq 1 ]]; then
    case "$BRANCH" in
        master|release/v*|feature/*|fix/*|perf/*|chore/*|ci/*|docs/*) ;;
        *)
            echo "error: prerelease '$VERSION' must be cut from master, release/v*, or a work branch (feature/*, fix/*, perf/*, chore/*, ci/*, docs/*); current branch is '$BRANCH'." >&2
            exit 1 ;;
    esac
else
    if [[ ! "$BRANCH" =~ ^release/v ]]; then
        echo "error: stable version '$VERSION' must be cut from a 'release/v*' branch (got '$BRANCH'). See docs/BRANCHING.md." >&2
        exit 1
    fi
fi

step "Verifying clean working tree"
if [[ -n "$(git status --porcelain)" ]]; then
    echo "error: working tree is dirty. Commit or stash before releasing." >&2
    git status --short >&2
    exit 1
fi

step "Verifying tag $TAG does not already exist"
if git rev-parse -q --verify "refs/tags/$TAG" >/dev/null; then
    echo "error: tag '$TAG' already exists locally." >&2
    exit 1
fi

if [[ "$SKIP_TESTS" -eq 0 ]]; then
    step "Running dotnet test"
    dotnet test --nologo
else
    echo "warning: skipping tests (--skip-tests)" >&2
fi

step "Rewriting <Version> in Directory.Build.props -> $VERSION"
if [[ ! -f "$PROPS_PATH" ]]; then
    echo "error: $PROPS_PATH not found." >&2
    exit 1
fi
if ! grep -q '<Version>[^<]*</Version>' "$PROPS_PATH"; then
    echo "error: no <Version>...</Version> element found in $PROPS_PATH." >&2
    exit 1
fi
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT
sed "s|<Version>[^<]*</Version>|<Version>$VERSION</Version>|" "$PROPS_PATH" > "$TMP"
mv "$TMP" "$PROPS_PATH"
trap - EXIT

step "Committing and tagging"
git add -- "$PROPS_PATH"
if git diff --cached --quiet; then
    echo "warning: Directory.Build.props already at $VERSION; skipping commit."
else
    git commit -m "chore: bump version to $VERSION"
fi
git tag -a "$TAG" -m "Release $VERSION"

step "Pushing branch '$BRANCH' and tag '$TAG' to '$REMOTE'"
git push "$REMOTE" "$BRANCH"
git push "$REMOTE" "$TAG"

# Open a backmerge PR from the release branch into master. This is best-effort
# — if `gh` is unavailable or the run is on master itself, print the manual
# command and exit clean.
if [[ "$OPEN_PR" -eq 1 && "$BRANCH" =~ ^release/v && "$BRANCH" != "master" ]]; then
    if command -v gh >/dev/null 2>&1; then
        step "Opening backmerge PR ($BRANCH -> master)"
        gh pr create \
            --base master \
            --head "$BRANCH" \
            --title "chore: backmerge $TAG" \
            --body "Backmerges the \`$TAG\` release into \`master\`. Auto-generated by \`scripts/release.sh\`." \
            || echo "warning: 'gh pr create' failed; open the PR manually."
    else
        echo "note: GitHub CLI ('gh') not found. Open the backmerge PR manually:"
        echo "      gh pr create --base master --head $BRANCH --title 'chore: backmerge $TAG'"
    fi
fi

printf '\033[32mReleased %s (tag %s) from %s.\033[0m\n' "$VERSION" "$TAG" "$BRANCH"
